<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-B2426KB" ignored="0" name="Test" tests="10" failures="2" timestamp="18 Jun 2020 10:27:31 GMT" time="0.045" errors="0">
  <testcase name="test1" time="0.008" classname="com.retryfailedtestcases.Mytests"/>
  <testcase name="test2" time="0.002" classname="com.retryfailedtestcases.Mytests">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.001" classname="com.retryfailedtestcases.Mytests">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.001" classname="com.retryfailedtestcases.Mytests">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.001" classname="com.retryfailedtestcases.Mytests">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.retryfailedtestcases.Mytests.test2(Mytests.java:38)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test3" time="0.001" classname="com.retryfailedtestcases.Mytests"/>
  <testcase name="test4" time="0.001" classname="com.retryfailedtestcases.Mytests">
    <skipped/>
  </testcase> <!-- test4 -->
  <testcase name="test4" time="0.002" classname="com.retryfailedtestcases.Mytests">
    <skipped/>
  </testcase> <!-- test4 -->
  <testcase name="test4" time="0.0" classname="com.retryfailedtestcases.Mytests">
    <skipped/>
  </testcase> <!-- test4 -->
  <testcase name="test4" time="0.001" classname="com.retryfailedtestcases.Mytests">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.retryfailedtestcases.Mytests.test4(Mytests.java:50)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test4 -->
</testsuite> <!-- Test -->
